# Generated by Django 5.1.7 on 2025-03-10 04:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('delivery_system', '0002_delivery_created_by_alter_client_email_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='delivery',
            name='duration',
        ),
        migrations.AddField(
            model_name='delivery',
            name='estimated_duration',
            field=models.FloatField(blank=True, null=True, verbose_name='Duración estimada (min)'),
        ),
    ]
